name: kotest_ci

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant gradle permission
        run: chmod +x ./gradlew

      - name: Run test
        run: ./gradlew test
